apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-demo
  labels:
    app: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 5 # Keeps track of your last 5 rollouts for easy rollback
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Allows 1 extra pod above replica count during update
      maxUnavailable: 0  # Guarantees all 3 original pods stay up until new ones are ready
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1 # Start with this version, then change it to practice rollouts
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"