apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-demo
  labels:
    app: nginx
  annotations:
    # This note will show up in your rollout history logs!
    kubernetes.io/change-cause: "Upgrading nginx to version 1.26.0"
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.0 # Updated from 1.25.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
