services:
  frontend:
    image: nginx
    ports:
      - "8080:80"

  
  backend:
    build: ./backend
    networks:
      - frontend_network
      - backend_network
    image: nginx

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
    volumes:
      - db_data:/var/lib/mysql
  